### ISSUE TITLE
It all force closes when clicking "select folder" in advanced settings for changing where it installs.

### ISSUE THREAD

**Issue by E314C-LR** [SkyblockClient/SkyClient-Windows#43]
Can't change install location, don't want it in with my normal Minecraft at all, but that is not possible in the Java version, nor here due to the whole thing force closing itself whenever the button is selected. The text field underneath the "select folder" is unmodifiable as well, and idk if you are meant to be able to or not, either way changing the install location is not possible.

![image](https://github.com/SkyblockClient/SkyblockClient/assets/59571867/b8cd901f-ea4d-4c32-95c0-6ede1222dd25)
Image is just for context, and is the executable when first opened to click advanced settings, the selections of items in the two checkbox fields change nothing with this process when it force closes.

![image](https://github.com/SkyblockClient/SkyblockClient/assets/59571867/3c0285b6-6cd9-4c6b-a525-ea7dbf9b51b2)
The error that it outputs as it closes.

**Comment by Intancote** [comment]
Getting the same error myself also when trying to change location
![image](https://github.com/SkyblockClient/SkyblockClient/assets/91847315/6c994e3a-a0ce-4099-89b8-ea294e13b0fe)

**Comment by cryolithic** [comment]
I also get this

**Comment by Wyvest** [comment]
Fixed in 1.3.13 (building rn)
