### ISSUE TITLE
Mods not updating

### ISSUE THREAD

**Issue by FrankPT202** [SkyblockClient/SkyClient-Windows#45]
every time I open skyclient it tells me I have mods to update and every time it fails to update those mods. I have tried to manually update them by replacing the files but it keeps saying I need to update them.
![image_2024-04-03_122726926](https://github.com/SkyblockClient/SkyblockClient/assets/150800320/ee57a829-efc8-476e-9113-c0b628c47949)
![image_2024-04-03_122742085](https://github.com/SkyblockClient/SkyblockClient/assets/150800320/6a9e1cf5-d22a-480e-9acc-c8d8a8ef8e4f)

**Comment by beeinaboats** [comment]
Been having the exact same problem

**Comment by Wyvest** [comment]
Please go to discord.gg/skyclient for support
